name: send_log
description: Log support with e-mail sending.
version: 1.1.9
homepage: https://github.com/deakjahn/send_log

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  archive: ^4.0.7
  clock: ^1.1.1
  logging: ^1.2.0
  logging_appenders: ^1.4.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: hu.co.tramontana.sendlog
        pluginClass: SendLogPlugin
      ios:
        pluginClass: SendLogPlugin

funding:
  - https://buymeacoffee.com/deakjahn

topics:
  - flutter
  - logging
  - e-mail